stages:
#  - build
  - test
#  - deploy

#build:
#  stage: build
#  image: php:7-fpm
#  script:
#    - "php -v"
#    - "php composer.phar install"
#  tags:
#    - php
#    - php7-fpm

test:
  stage: test
  image: merorafael/php:7.0-fpm
  script:
    - "php -v"
    - "php composer.phar install"
    - "php vendor/bin/phpunit"
  tags:
    - php
    - php7-fpm

#deploy:
#  stage: deploy
#  image: php:7-fpm
#  script:
#    - "php -v"
#  tags:
#    - php
#    - php7-fpm
