stages:
  - build
  - test
  - deploy

build:
  stage: build
  image: php:7-fpm
  script:
    - "php -v"
  tags:
    - php
    - php7-fpm

test:
  stage: test
  image: php:7-fpm
  script:
    - "php -v"
  tags:
    - php
    - php7-fpm

deploy:
  stage: deploy
  image: php:7-fpm
  script:
    - "php -v"
  tags:
    - php
    - php7-fpm
