nginx:
    image: nginx:latest
    ports:
        - "8080:80"
    volumes:
        - .:/var/www/app
        - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
        - php

php:
    image: php:7-fpm
    volumes:
        - .:/var/www/app